### PR TITLE
Use injection

### PR DESCRIPTION
**Pull request by shidayang**
## Brief change log
1. Add the hadoop-apache dependency to avoid the need for users to manually add flink-shaded-hadoop--uber-.jar.
2. Change the packaging type from JAR to TAR.
3. Introduce injection

### CODE REVIEW

**Comment by shidayang** [comment]
@JingsongLi PTAL

**Review by JingsongLi — COMMENTED** [review]
Very thanks @shidayang for your contribution.

Can you prepare documentation PR at the same time too?

**Comment by shidayang** [comment]
> Very thanks @shidayang for your contribution.
> 
> Can you prepare documentation PR at the same time too?

Sure

**Comment by shidayang** [comment]
> Very thanks @shidayang for your contribution.
> 
> Can you prepare documentation PR at the same time too?

Doc pr: https://github.com/apache/incubator-paimon/pull/2542

**Review by JingsongLi — APPROVED** [review]
+1 thanks @shidayang

**Pull request merged**
